### ISSUE TITLE
Greyscale Option

### ISSUE THREAD

**Issue by kes1** [OrdnanceSurvey/OS-OpenMap-Local-stylesheets#1]
These stylesheets are great, especially now that you've added advanced labelling for ArcMap users with Maplex.

Would it be possible to also share a gresycale or single-colour option alongside the backdrop colours?

**Comment by charleyglynn** [comment]
Hi @kes1, thanks for the feedback. Glad you like the advanced labelling.

Greyscale is something that we will consider for future releases. In the meantime some people have already converted the styles themselves and re-shared, including these QGIS stylesheets from @mixedbredie https://github.com/mixedbredie/QGIS-styles
