### ISSUE TITLE
2 GeoServer directories in 'ESRI Shapfile stylesheets'

### ISSUE THREAD

**Issue by jnicho02** [OrdnanceSurvey/OS-OpenMap-Local-stylesheets#10]
I suspect you noticed that the case was wrong and updated it...unfortunately git can be case insensitive when you don't want it to be (e.g. on Mac but not Windows)... 'ESRI Shapfile stylesheets/Geoserver stylesheets (SLD)' and 'ESRI Shapfile stylesheets/GeoServer stylesheets (SLD)'.

You might have to go all git command line on it: git mv --force filename Filename ...but don't take my word on that.

...and while i'm at it 'ESRI Shapfile'?

Sorry for the pedantry

**Comment by egil1978** [comment]
All done. Thanks for pointing this out :)
