### ISSUE TITLE
Layer ordering screenshots missing from readmes

### ISSUE THREAD

**Issue by RobQuincey** [OrdnanceSurvey/OS-OpenMap-Local-stylesheets#11]
A number of the screenshots in the readmes are missing. Particularly important are the suggested layer group orderings, for example here - https://github.com/OrdnanceSurvey/OS-OpenMap-Local-stylesheets/tree/master/GML%20stylesheets/GeoServer%20stylesheets%20(SLD)/Full%20colour%20style - I can't find any relevant PDFs either.

**Comment by egil1978** [comment]
Hi, thanks for pointing this out. If ok i will address this first thing tomorrow morning. Apologies that these are not displaying.

**Comment by RobQuincey** [comment]
That's great. I found the Quick Start guide just now which contains the screenshot, so I'm in business anyway! Great resource.

**Comment by egil1978** [comment]
Hi, I have managed to fix the problem this afternoon so all screenshots are now displaying. Thanks for the heads-up and kind comments :)
