### ISSUE TITLE
Recommended layer order

### ISSUE THREAD

**Issue by mpdaly** [OrdnanceSurvey/OS-OpenMap-Local-stylesheets#13]
The recommended layer orders for different stylesheets do not agree.

LYR:

![LYR](https://raw.githubusercontent.com/OrdnanceSurvey/OS-OpenMap-Local-stylesheets/master/ESRI%20Shapefile%20stylesheets/ESRI%20stylesheets%20%28LYR%29/Full%20colour%20style/images/OML_FC_layer_order.png)

**NB** also has 'RoadFill' and 'RoadCase level 0', which the others don't

QML:

![QML](https://raw.githubusercontent.com/OrdnanceSurvey/OS-OpenMap-Local-stylesheets/master/Geopackage%20stylesheets/QGIS%20Stylesheets%20(QML)/Backdrop%20style/images/OML_layer_order.png)

SLD:

![SLD](https://raw.githubusercontent.com/OrdnanceSurvey/OS-OpenMap-Local-stylesheets/master/GML%20stylesheets/GeoServer%20stylesheets%20%28SLD%29/Backdrop%20style/images/OML_layer_order.png)

**NB** also missing 'CarChargingPoint', which the others have

**Comment by egil1978** [comment]
Thanks for pointing this out Martin and apologies for the delay. All fixed now.
