### ISSUE TITLE
Geopackage ESRI Stylesheets

### ISSUE THREAD

**Issue by SeanMcV** [OrdnanceSurvey/OS-OpenMap-Local-stylesheets#14]
I am having a problem when working with the geopackage stylesheets within ESRI ArcMap 10.7.1.

I run through the supplied instructions as far as adding data and importing the LYR file.

When I go to the Layer Properties on any of the layers, on the Source tab the option for Change Source is not available, only Change Query.

I can only get Change Source when importing the regular ESRI stylesheet, but then the queries set within some of the layers do not work, because of the different field names.

Is anyone able to help?

**Comment by egil1978** [comment]
Hi Sean, just to let you know a fix has been found for this and new layer files will be available from this repo shortly.

**Comment by egil1978** [comment]
Hi Sean, the new layer files can be downloaded from this repo now and should solve the problems you were having. Let me know if they work ok and ill then close the issue. Thanks :)

**Comment by egil1978** [comment]
Issue closed
