### ISSUE TITLE
CartoCSS format

### ISSUE THREAD

**Issue by GetTheData** [OrdnanceSurvey/OS-OpenMap-Local-stylesheets#16]
Is it possible to make these available in CartoCSS format please?

**Comment by charleyglynn** [comment]
Hi @GetTheData thanks for your interest, as with the Mapnik styles. I'm afraid at this time we don't have any plans to create CartoCSS stylesheet formats.

If others were to create them we would be happy to add them to the repo.

Thanks
Charley
