### ISSUE TITLE
Labels issue

### ISSUE THREAD

**Issue by twutmc** [OrdnanceSurvey/OS-OpenMap-Local-stylesheets#2]
The Open Map Local style sheets load the style but will not load the text labels in QGIS with sld or qml?

**Comment by charleyglynn** [comment]
Thank you for the feedback.

Are you using QGIS 2.12 or more recent? If so, the stylesheet for NamedPlace won't work as it was created in an earlier version before the label engine was upgraded. It is our intention to create new QML stylesheets for all of our products that will work with 2.12+ and they will be released soon.

I will in the meantime make this clear in the repository.

Charley

**Comment by twutmc** [comment]
Hi there,

We're using QGIS 2.12.3. Thanks for the update, I'll check back in the coming days.

**Comment by twutmc** [comment]
Any update on when the new version QML's for QGIS will be posted that fix the labelling issue?

**Comment by egil1978** [comment]
Hi necautmc, i found a work around for this last week. Its a bit crude but should work. Ill post it up here shortly

**Comment by egil1978** [comment]
1. Load your data into QGIS as normal
2. Before attaching your QML file to your data ensure the drop down for labeling is set to **No labels**
3. Load your QML file
4. Change your labeling drop down to **Rule-based labeling**
5. Now change it to **Show labels for this layer**
6. The label properties should now be displaying - Press apply

We would love to know if this fix works for you so please do let us know.

**Comment by twutmc** [comment]
That looks to have worked. Thank you for your help.
