### ISSUE TITLE
Add GeoServer SLD styles

### ISSUE THREAD

**Issue by coxp** [OrdnanceSurvey/OS-OpenMap-Local-stylesheets#3]
Pretty please :)

**Comment by egil1978** [comment]
Hi,
The SLD's for the backdrop style is ready to be uploaded to GitHub, however i am in the process of completing the documentation that goes with the SLD's. As soon as that is done i will upload them.
Im hoping that this will happen sometime next week.

**Comment by coxp** [comment]
That's fantastic news :thumbsup:.

Would it be possible to get SLD files for Strategi and Meridian2 as well?

**Comment by egil1978** [comment]
Hi Paul, the backdrop SLD's for OpenMap-Local are now available. I'd be interested in any feedback you have :)

**Comment by coxp** [comment]
Hi,

There are a few errors with the Roads style using property names from the GML files rather than the Shapefiles (do you accept pull requests to this repository? I couldn't see any contribution guidelines).

https://github.com/OrdnanceSurvey/OS-OpenMap-Local-stylesheets/blob/master/ESRI%20Shapfile%20stylesheets/Geoserver%20stylesheets%20(SLD)/Backdrop%20style/OML_Roads_backdrop.sld#L309

There is also a stray character typo in the same file

https://github.com/OrdnanceSurvey/OS-OpenMap-Local-stylesheets/blob/master/ESRI%20Shapfile%20stylesheets/Geoserver%20stylesheets%20(SLD)/Backdrop%20style/OML_Roads_backdrop.sld#L90

Also, the styles don't look quite as nice as I'd hoped and don't match the VectorMap District styles when creating a combined map. The roads and the text in particular could do with some work. For instance, compare the following image at the same location as the example shown on the OpenMap Local home page (https://www.ordnancesurvey.co.uk/business-and-government/products/os-open-map-local.html)

![os-openmap-local](https://cloud.githubusercontent.com/assets/447011/13645869/e3508784-e624-11e5-8ed3-1b664a40fc9a.png)

**Comment by coxp** [comment]
For comparison, this is the same location shown with the OS VectorMap District styling from here, https://github.com/OrdnanceSurvey/OS-VectorMap-District-stylesheets/tree/master/ESRI%20Shapefile%20stylesheets/GeoServer%20stylesheets%20(SLD)/Full%20Colour%20style.

![os-vectormap-district](https://cloud.githubusercontent.com/assets/447011/13645987/5d4a1154-e625-11e5-85e9-5331d7c3d1e5.png)

**Comment by egil1978** [comment]
Thanks for the feedback. Looks like there are a few problems with the roads layer. Ill take a look and get back to you with amended SLD's ASAP

**Comment by sequel63** [comment]
Any news on the roads issue? I'd love to get fixed SLD too.

**Comment by ghost** [comment]
sequel63, apologies for the delay, there are a number of issues with the roads stylesheet which we are currently investigating. We'll keep you posted.

**Comment by egil1978** [comment]
The SLD's for OML have now been corrected and are available for download. SLD's for Strategi are also available
