### ISSUE TITLE
Stylesheets for SVG

### ISSUE THREAD

**Issue by Scott07uk** [OrdnanceSurvey/OS-OpenMap-Local-stylesheets#4]
Having used your Master Map product for work, where there is an XSLT Style Sheet which can be used to transform the GML into SVG images it would be really useful if there was a simmilar stylesheet for these maps.  I know this is a slower and more resource intensive approach for building maps, but in my view it offers the highest degree of customisablity as you can dynamically control what data appears in the GML, and you can control how the presentation of the maps work though instructions added to a "header" in the GML.

**Comment by charleyglynn** [comment]
Thanks for the feedback @Scott07uk 

We provide stylesheets in 3 formats (QML, SLD and Layerfile) as a good starter for 10 for most GIS use cases. The styling information is intrinsically available within the stylesheets so it would be possible to adapt the styles into different formats. At this moment in time it's not our intention to provide any further formats.

Thanks
Charley
