### ISSUE TITLE
CarChargingPoint Symbol

### ISSUE THREAD

**Issue by alexR88** [OrdnanceSurvey/OS-OpenMap-Local-stylesheets#6]
When applying the ESRI stylesheet 'OpenMapLocal-FullColour.lyr' the Car Charging Points are displayed as blue 'D's as opposed to the symbol shown on the product information page https://www.ordnancesurvey.co.uk/business-and-government/products/os-open-map-local.html. I've tried the qml file for QGIS and get the same result.

Is this correct? Thanks

![carchargingpoints](https://cloud.githubusercontent.com/assets/23264348/20050862/a288703c-a4c3-11e6-942a-f7dd2743caf9.PNG)

**Comment by egil1978** [comment]
Hi, in order for you to display the symbol you will need to install the font. To do this copy the font file 'OSOpenMapLocal-Normal_0.otf' into your systems font directory (on Windows machines this is (C:\Windows\Fonts)

**Comment by alexR88** [comment]
that's great, thank you!
