### ISSUE TITLE
Layer file with the raster label settings

### ISSUE THREAD

**Issue by alexR88** [OrdnanceSurvey/OS-OpenMap-Local-stylesheets#7]
The labelling on the raster version of this dataset is great. This is a bit of a long shot but is there a layer file available that contains the raster label settings that I can then apply to the vector data? Thanks

**Comment by charleyglynn** [comment]
We don't have anything other than the LYR files in this repo: https://github.com/OrdnanceSurvey/OS-OpenMap-Local-stylesheets/tree/master/ESRI%20Shapefile%20stylesheets/ESRI%20stylesheets%20(LYR)
